### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by citizenthr33** [darrenwatt/docker-spotify-ripper#1]
hey there,
i just wanted to ask if you could show me a sample installation process. i have very few experience with docker and would be happy about that becaus i think it  is an awesome idea to use docker for he ripper!

Thanks for your help!

**Comment by darrenwatt** [comment]
Hi, I'd suggest running through the Docker basics here:
https://docs.docker.com/engine/getstarted/

Once you have the initial setup running, the commands listed in Readme.MD should work.

**Comment by darrenwatt** [comment]
I actually felt bad that this was a bit dismissive so here's a full write up. Hope it helps!
https://darrenwatt.com/spotify-ripper-as-a-docker-container/

**Comment by citizenthr33** [comment]
Thank you a lot! You helped me very well with it and probably a lot of other people too!
Keep it up and have a good time.
